### ISSUE TITLE
Logo for "the woodcraft"

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-thewoodcraft#1]
Create a logo for this company. 

It's a small business that does custom wood-work. Wood-work as in it'll create custom furniture for you out of wood. It'll also remodel your home for you if need be. Basically if you want a desk made out of wood, they can make it for you.

In terms of emotion: 

- option1 Timeless, established

- option2 Modern, sliiiiightly playful

IMPORTANT: I want you to work with @AaronAguilar on this. Collaborate and show me progress every two days, whether it be sketches or a list of ideas you've come up with. 

due: 
8-31-15  9p

updated due:
11-11-15      1p

**Comment by rodneystrong** [comment]
Adding @vanderbeam to this task. 3 of you, please coordinate. 

This is an experiment so your feedback is extremely necessary.

**Comment by rodneystrong** [comment]
Heads up. Client would like a different take on the logo. He sent me this image as inspiration. 
<img width="726" alt="screen shot 2015-11-06 at 1 04 10 pm" src="https://cloud.githubusercontent.com/assets/539962/11008661/e9dc1938-8486-11e5-9d7d-da9189360444.png">

I want all three of you to work on separate options again, so three new logos total by this Wednesday. 
@vanderbeam @jperez4509 @AaronAguilar 

due:
11-6-15    1p

**Comment by rodneystrong** [comment]
All of you, please comment here by Saturday 1pm if you're able to show me some progress this Monday. 

Just progress, doesn't have to be done.

**Comment by vanderbeam** [comment]
Yep. Already started.

**Comment by jperez4509** [comment]
I will have something

**Comment by rodneystrong** [comment]
@AaronAguilar yo, please comment here

**Comment by AaronAguilar** [comment]
Sorry, I'll have something by Monday.

**Comment by vanderbeam** [comment]
![logo_redo](https://cloud.githubusercontent.com/assets/12962001/11051137/6988bb56-8701-11e5-82c1-f7c5ca1961d1.png)

It was my priority to find a font I want for this design. The design idea itself is still very much early in development.

**Comment by jperez4509** [comment]
First Design. After discussing the design with you I understand you want me to play around with the saw.  I still want to submit this initial design because I really feel that the client needs a simple and clean design. 

<img width="1116" alt="screen shot 2015-11-07 at 9 39 50 pm" src="https://cloud.githubusercontent.com/assets/8659273/11051211/242ad26e-8702-11e5-9586-cdf3f31112e9.png">

I will should have another design for you by Tomorrow night or Wednesday that follows more closely what we discussed today.

**Comment by vanderbeam** [comment]
Auuugh Joel that's so cool

**Comment by jperez4509** [comment]
@vanderbeam Thanks... I  really like your concept of the saw. The second to the last one, It has movement and makes the logo look more exciting.

**Comment by AaronAguilar** [comment]
![redesign-logo-1-01](https://cloud.githubusercontent.com/assets/10875354/11051353/4b72123c-8703-11e5-974b-7e6fe8941a7e.jpg)
![redesign-logo-2](https://cloud.githubusercontent.com/assets/10875354/11051352/4b7013e2-8703-11e5-8f37-3161c6bd5db6.png)

Still playing around with how I want to incorporate the saw, whether to use it as a badge or to balance out the typography, but here's what I have so far.

**Comment by AaronAguilar** [comment]
@vanderbeam Nice use of the colors! I forgot that the client wanted an eco green color on the logo.

**Comment by vanderbeam** [comment]
@rodneystrong Sorry for the delay. Had some technical issues today.

https://drive.google.com/file/d/0B7-L_YWYH3_YaG9uMUJQVXF2Q1E/view?usp=sharing
https://drive.google.com/file/d/0B7-L_YWYH3_YUjlkZnBnYnNldXc/view?usp=sharing
https://drive.google.com/file/d/0B7-L_YWYH3_YQ0dvQ3VLUmFydW8/view?usp=sharing

**Comment by jperez4509** [comment]
@rodneystrong Here are my links for the logo style guides I created.
https://drive.google.com/file/d/0B8EN2ZGYf3v5VlQ2TURVQkota2c/view?usp=sharing
https://drive.google.com/file/d/0B8EN2ZGYf3v5TE5wT2RmbGhTOUk/view?usp=sharing

**Comment by AaronAguilar** [comment]
https://drive.google.com/file/d/0BwNEeMVrMpDLaVNwZU1hTTloREE/view?usp=sharing

https://drive.google.com/file/d/0BwNEeMVrMpDLd2l6cjZpbDNjR1E/view?usp=sharing

**Comment by rodneystrong** [comment]
GREAT job on the designs everyone! Rich came in yesterday and chose @jperez4509's circular option.
