### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-thewoodcraft#10]
Our contact info is wrong on our website.
559-312-8909
1343 N. Crystal
Fresno, CA. 93726
Please make the changes

due:
1-14-16   12p

**Comment by rodneystrong** [comment]
Also, please upload this to FTP

**Comment by rampage1213** [comment]
Done!

**Comment by rodneystrong** [comment]
-___-)   these changes don't see to be done... Please push to the gh-pages branch AND ftp

**Comment by rampage1213** [comment]
This issue is live it's been FTP. Joel and I are still working on lazy load and masonry that's why it's not live on gh-pages.

**Comment by rodneystrong** [comment]
I'm looking at the live URL right now, the contact info is wrong. 

Also, the "Call for a quote" section near the top of the site has the wrong number as well.

**Comment by rampage1213** [comment]
Done! FTP!
