### ISSUE TITLE
create site from template

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-thewoodcraft#2]
Build out the site from the usual template we use (or go with a different template if you feel compelled)

Use images from this drive folder: https://drive.google.com/folderview?id=0BzVFl2mibGTnflY0WmJkbkYyNU9GZFVwNDVxSnJMMTN3MFJnZTQyQktxTEZQZjRtbDlMd28&usp=sharing

I also want you to use this specific image as the first slide in the slider: https://drive.google.com/file/d/0BzVFl2mibGTncG5paENoM1RDVzQ/view?usp=sharing

Crop it creatively to look good but make sure the slider as a whole isn't taller than 350px. 

**Updated 8-27-15 changed due date**

due:
8-31-15   10p

**Comment by rodneystrong** [comment]
Joel, I fixed your code and reset it to your original first commit. 

All you need to do now is pull the latest from the master and gh-pages branch. 

After that you can then copy.paste your new code that you worked on separately into the files.

Let me know if you have any questions.

**Comment by jperez4509** [comment]
Done. Thanks again for your help with fixing my git commits.
