### ISSUE TITLE
Add logo and optimize the site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-thewoodcraft#6]
Add your logo to the site

Make necessary color adjustments

Make sure the site doesn't take forever to load.

due:
11-16-15    5p

**Comment by jperez4509** [comment]
Here is the link for the final version of logo: https://drive.google.com/folderview?id=0B8EN2ZGYf3v5fkpfTE9ScW1nQ3ZsQ09KV19uRzh5WmtaVVdiZEhRQlA2UjAwSEtXSXRDYlE&usp=sharing

**Comment by jperez4509** [comment]
Site should be complete. I just need to create the favicon

**Comment by jperez4509** [comment]
Done.
