### ISSUE TITLE
Content from client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-thewoodcraft#8]
Here are her notes: 
https://drive.google.com/a/editllc.com/file/d/0B88_mCI0OTGkMDJRM3F6YWhHTDg/view?usp=sharing

>Sorry for the slowness. I've attached some copy for the site. We've decided to consolidate the "Recycle" and "Green" sections into one "Sustainability" section. Hope that makes sense. Let me know if you have questions about anything I've sent over.

>One last thing, the words "Quality Woodworking" kinda looks like the name of another company. Is it possible to include "Providing professionalism and quality cabinetry for 30 years" in that space?

>I think that will work for now. 

due:
12-30-15    6p

updated due:
1-1-16  8p

**Comment by rampage1213** [comment]
Done!

**Comment by rodneystrong** [comment]
Good job with this dude. I'm gonna have to make a judgement call that goes against our client's instructions. 

If you look at the site, you'll notice that @jperez4509 did a good job separating each section with a unique layout without needing to create an actual horizontal line divider. (the top hero image is separated from the "Services" section" with the phone number and the green background color, the "Services section is separated from the "testimonials" section with a green bg color, the "testimonials" section is separated from the "portfolio" (our work) section with a black bg color and the masonry image layout, etc (you get the hint right?) ) 

Knowing this, Joel unfortunately put the "About us" section near the bottom. This alone isn't wrong, but the word Doc that Marci gave us alludes that the 1st paragraph in the "Services" section is better served as an "About Us" paragraph. Notice that we still have 'lorem ipsum' latin for their "About Us" section. 

Here's what I want you to do: 
-Move the "about us" section to right below the "Call us for a quote" phone number 

-The "about us" and "services" should now be on top of each other, but this doesn't look well separated now. 

-Move the "testimonials" section to right above the "services" section; now the "about us" and "services" are well separated while still respecting Joel's thematic layout

-Remove the "Over 30 years, we’ve designed and built hundreds of  beautiful custom cabinets for homes and innovative.."  paragraph from the "services" section and put that in the "about us" section". 

How do you think this page looks now? Worse, better or no different? 

Please give me your opinion as well Joel. 

due:
12-1-15  8p

**Comment by rampage1213** [comment]
This is done! and I do like this it puts all the content at the top of the page for the user to read then see his work and contact him at the bottom

**Comment by rodneystrong** [comment]
Sorry kiddo, can't close until I get feedback from @jperez4509

**Comment by jperez4509** [comment]
@rodneystrong and @rampage1213: I actually do like the new flow of the site. It works for this type of site because the site does not sale a particular product but works more as a branding site where prospective clients can go and learn more about The Woodcraft. The new flow/layout informs the visitor about who the company is, what they do, displays the work, and how to contact them. 

Usually when a site is used to sale a product I like putting the About Us section at the end because the product is the number one focus. But when a site is used to brand a company I do agree that the About Us/Mission/History sections should be front and center.

**Comment by rodneystrong** [comment]
Good stuff. Thanks for the input both of you.
